apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
        - image: redis:latest
          name: redis-deployment
          ports:
            - containerPort: 6379
          resources:
          volumeMounts:
            - name: redis-storage
              mountPath: /data/redis
      volume:
        - name: redis-storage
---
apiVersion: v1
kind: Service
metadata:
  name: redis-deployment
spec:
  selector:
    app: redis-deployment
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
